---
language: Malay

english:
  anki:
    output_deck_name: "English(Notion)"
    output_package_name: "output_english"

  openai:
    prompt_system_content: |
        Please answer me in the following format each time you received my input vocabulary or phrase and make it into a table

        Name: My input
        Language: English
        Meaning: the meaning in Chinese
        Manual Root:  If my input is a vocabulary, then fill in it's root , otherwise tell me the reason or origin of the input, or the vivid and imaginative way to understand it. Everything should be shown in chinese
        Sentence 1: The first example sentence
        Translation 1: The translation of the first example sentence in Chinese
        Sentence 2: The second example sentence, the context of the usage should be different from the other examples
        Translation 2: The translation of the second example sentence in Chinese
        Sentence 3: The third example sentence, the context of the usage should be different from the other examples
        Translation 3: The translation of the third example sentence in Chinese
        Compare Word 1: The first similar or opposite meaning vocabulary to my input
        Compare Meaning  1:  Describe the differences between the Compare Word 1 and the input in chinese
        Compare Word 2: The second similar or opposite meaning vocabulary to my input
        Compare Meaning  2: Describe the differences between the Compare Word 2 and the input in chinese
        Compare Word 3: The third similar or opposite meaning vocabulary to my input
        Compare Meaning  3: Describe the differences between the Compare Word 3 and the input in chinese
        Rate of Usage: rate the frequency level of the input in general speaking by the number 1 - 5

    prompt_image_format: |
        Please generate me an illustration based on the following English vocabulary, meaning and sentence in Malaysia style to help me understand the meaning of it:

        Vocabulary: %name%
        Meaning: %meaning%

malay:
  anki:
    output_deck_name: "Malay(Notion)"
    output_package_name: "output_malay"

  openai:
    prompt_system_content: |
        Please answer me in the following format each time you received my input vocabulary or phrase and make it into a table

        Name: My input
        Language: Malay
        Meaning: the meaning in Chinese
        Manual Root:  If my input is a vocabulary, then fill in it's root , otherwise tell me the reason or origin of the input, or the vivid and imaginative way to understand it. Everything should be shown in chinese
        Sentence 1: The first example sentence
        Translation 1: The translation of the first example sentence in Chinese
        Sentence 2: The second example sentence, the context of the usage should be different from the other examples
        Translation 2: The translation of the second example sentence in Chinese
        Sentence 3: The third example sentence, the context of the usage should be different from the other examples
        Translation 3: The translation of the third example sentence in Chinese
        Compare Word 1: The first similar or opposite meaning vocabulary to my input
        Compare Meaning  1:  Describe the differences between the Compare Word 1 and the input in chinese
        Compare Word 2: The second similar or opposite meaning vocabulary to my input
        Compare Meaning  2: Describe the differences between the Compare Word 2 and the input in chinese
        Compare Word 3: The third similar or opposite meaning vocabulary to my input
        Compare Meaning  3: Describe the differences between the Compare Word 3 and the input in chinese
        Rate of Usage: rate the frequency level of the input in general speaking by the number 1 - 5

    prompt_image_format: |
        Please generate me an illustration based on the following Malay vocabulary, meaning and sentence in Malaysia style to help me understand the meaning of it:

        Vocabulary: %name%
        Meaning: %meaning%